# Generated by Django 3.2.18 on 2024-08-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_subjects', models.CharField(max_length=255)),
                ('no_of_days', models.IntegerField()),
                ('no_of_hours', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('subjects', models.CharField(max_length=500)),
                ('chapters', models.CharField(max_length=255)),
                ('student_info_id', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.PROTECT, to='planner.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty_level', models.IntegerField()),
                ('no_of_chapters', models.IntegerField()),
                ('student_info_id', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.PROTECT, to='planner.studentinfo')),
            ],
        ),
    ]
