# Generated by Django 3.2.18 on 2024-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
